### ISSUE TITLE
dependency check psr/log

### ISSUE THREAD

**Issue by moreishi** [PayMaya/PayMaya-PHP-SDK#25] opened 2020-06-29 16:05 UTC
on command 'compose require composer require "paymaya/paymaya-sdk:*"'

cli error appear: ''**Conclusion: don't install psr/log 1.0.2**"

Note: this is in Laravel 7

**Comment by rjarce** [comment] 2020-06-30 09:23
Closing as duplicate of #6

**Closed** 2020-07-03 00:32 UTC
Labels: duplicate
